apiVersion: v1
data:
  config.yaml: |
    decision_logs:
      console: true
    plugins:
      envoy_ext_authz_grpc:
        addr: ":9191"
        path: "envoy/authz/allow"
        enable-reflection: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-config
